apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: excalidraw-mcp
  namespace: agentgateway-system
spec:
  parentRefs:
  - name: agentgateway-proxy
    namespace: agentgateway-system
    sectionName: mcp
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /mcp-excalidraw
    backendRefs:
    - name: excalidraw-mcp
      group: agentgateway.dev
      kind: AgentgatewayBackend