apiVersion: v1
kind: Service
metadata:
  name: kagent-controller-nodeport
  namespace: kagent
  labels:
    app.kubernetes.io/part-of: kagent
    app.kubernetes.io/component: controller
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/name: kagent-enterprise
  ports:
    - name: controller
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 32083
