apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  annotations:
    description: Blocks OpenAI API keys (sk-...) in prompts
  labels:
    category: credential-protection
    demo: agentgateway
  name: 10-block-openai-api-keys
  namespace: agentgateway-system
spec:
  backend:
    ai:
      promptGuard:
        request:
        - regex:
            action: Reject
            matches:
            - sk-[a-zA-Z0-9]{20,}
          response:
            message: "\U0001F511 Blocked: OpenAI API key detected in prompt"
            statusCode: 403
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: multi-llm-route
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  annotations:
    description: Blocks GitHub personal access tokens in prompts
  labels:
    category: credential-protection
    demo: agentgateway
  name: 11-block-github-tokens
  namespace: agentgateway-system
spec:
  backend:
    ai:
      promptGuard:
        request:
        - regex:
            action: Reject
            matches:
            - ghp_[a-zA-Z0-9]{36}
          response:
            message: "\U0001F511 Blocked: GitHub token detected in prompt"
            statusCode: 403
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: multi-llm-route
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  annotations:
    description: Blocks Slack bot tokens in prompts
  labels:
    category: credential-protection
    demo: agentgateway
  name: 12-block-slack-tokens
  namespace: agentgateway-system
spec:
  backend:
    ai:
      promptGuard:
        request:
        - regex:
            action: Reject
            matches:
            - xoxb-[a-zA-Z0-9-]+
          response:
            message: "\U0001F511 Blocked: Slack token detected in prompt"
            statusCode: 403
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: multi-llm-route
