# Demo Policy: Safe Operations Only
# Allows everything except destructive operations
# (create repos, delete files, merge PRs, push code)
# Blocks 9 of 40 tools
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: github-mcp-safe-ops
  namespace: agentgateway-system
  labels:
    demo: "true"
    policy-type: safe-ops
  annotations:
    description: "Blocks destructive GitHub operations (create repo, delete, merge, push, fork)"
spec:
  targetRefs:
  - group: agentgateway.dev
    kind: AgentgatewayBackend
    name: github-mcp-backend
  backend:
    mcp:
      authorization:
        action: Allow
        policy:
          matchExpressions:
          - >-
            !(tool.name == 'create_repository' ||
            tool.name == 'create_or_update_file' ||
            tool.name == 'create_pull_request' ||
            tool.name == 'delete_file' ||
            tool.name == 'fork_repository' ||
            tool.name == 'merge_pull_request' ||
            tool.name == 'push_files' ||
            tool.name == 'update_pull_request' ||
            tool.name == 'update_pull_request_branch')
