# Demo Policy: Read-Only GitHub Access
# Only allows read/search/list operations — all writes blocked
# Allows 20 of 40 tools
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: github-mcp-read-only
  namespace: agentgateway-system
  labels:
    demo: "true"
    policy-type: read-only
  annotations:
    description: "Read-only GitHub access — only get/list/search/read operations allowed"
spec:
  targetRefs:
  - group: agentgateway.dev
    kind: AgentgatewayBackend
    name: github-mcp-backend
  backend:
    mcp:
      authorization:
        action: Allow
        policy:
          matchExpressions:
          - >-
            tool.name.startsWith('get_') ||
            tool.name.startsWith('list_') ||
            tool.name.startsWith('search_') ||
            tool.name == 'issue_read' ||
            tool.name == 'pull_request_read'
