###############################################################################
# MCP Authentication — Okta JWT Validation
# Validates JWTs on MCP tool routes. Unauthenticated requests are rejected
# before reaching any MCP tool server.
#
# Uses the OSS AgentgatewayPolicy backend.mcp.authentication field.
# JWKS fetched from Okta via ExternalName Service (okta-jwks).
###############################################################################
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: mcp-jwt-auth
  namespace: agentgateway-system
  labels:
    category: authentication
    demo: agentgateway
  annotations:
    description: >-
      Enforces Okta JWT validation on MCP routes. Only authenticated
      users/agents with valid tokens can access MCP tools.
spec:
  targetRefs:
  - kind: HTTPRoute
    name: mcp-slack
  - kind: HTTPRoute
    name: mcp-github
  backend:
    mcp:
      authentication:
        issuer: "https://integrator-7147223.okta.com/oauth2/aus104zseyg64swj3698"
        audiences:
        - "api://default"
        mode: Strict
        jwks:
          backendRef:
            name: okta-jwks
            port: 443
          jwksPath: "/oauth2/aus104zseyg64swj3698/v1/keys"
