###############################################################################
# MCP Tool Rate Limiting — Per-User
# Prevents runaway agents from exhausting upstream tool APIs.
# Rate limits are applied per authenticated user (from JWT sub claim).
###############################################################################
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: mcp-rate-limit
  namespace: agentgateway-system
  labels:
    category: rate-limiting
    demo: agentgateway
  annotations:
    description: >-
      Per-user rate limiting on MCP tool calls. Prevents any single user
      or agent from overwhelming Slack/GitHub APIs.
spec:
  targetRefs:
  - kind: HTTPRoute
    name: mcp-slack
  - kind: HTTPRoute
    name: mcp-github
  backend:
    mcp:
      rateLimit:
        requestsPerMinute: 30
        burstSize: 10
        perUser: true
      timeout:
        toolCallMs: 30000
