# Demo Policy: Block echo and get-env tools on MCP
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: mcp-block-echo-getenv
  namespace: agentgateway-system
  labels:
    demo: "true"
    policy-type: safe-ops
  annotations:
    description: "Blocks echo and get-env tools on MCP server"
spec:
  targetRefs:
  - group: agentgateway.dev
    kind: AgentgatewayBackend
    name: mcp-backend
  backend:
    mcp:
      authorization:
        action: Allow
        policy:
          matchExpressions:
          - >-
            !(tool.name == 'echo' || tool.name == 'get-env')
