apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: llm-agentgateway
  namespace: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  provider: OpenAI
  model: gpt-4o-mini-2024-07-18
  openAI:
    baseUrl: "http://172.16.10.168:30689/compatibility/v1"
